### ISSUE TITLE
IndexError: list index out of range when running inference

### ISSUE THREAD

**Issue by yformer** [gaopengcuhk/SMCA-DETR#11]
Hello,

When I run a modified d2go version of the code, it shows index error. Did you see this error before?

I wonder if my h_w is not set correctly? I feel confused about the samples[0], samples[1] (target)? It seems h_w is a concatenation of original images?  Then why we need a samples[1] to obtain h_w? So I change the code with the following code,

`h_w = torch.stack([torch.tensor([inst.shape[-2] for inst in samples]), torch.tensor([inst.shape[-1] for inst in samples])], dim=-1)`.

**Comment by lucasjinreal** [comment]
@yformer I think h, w is inputs height and width.

but I found even I set h_w normally, the first iter loss seems abnormal

**Comment by lucasjinreal** [comment]
@yformer My printed out is like this:

```
tensor([[ 841,  704],
        [ 666,  576],
        [ 727,  672],
        [ 891,  800],
        [1172,  800],
        [ 953,  736],
        [ 577,  480],
        [1058,  736]])


tensor([[ 910,  736],
        [ 958,  736],
        [ 811,  736],
        [ 895,  800],
        [ 860,  576],
        [ 736,  804],
        [1126,  736],
        [1021,  704]])


tensor([[ 480,  502],
        [1092,  736],
        [ 956,  672],
        [ 544,  556],
        [ 659,  576],
        [ 598,  544],
        [ 860,  704],
        [ 761,  736]])

```

**Comment by lucasjinreal** [comment]
@yformer However, I think my h, w is oppsited ......

**Comment by lucasjinreal** [comment]
@yformer @gaopengcuhk I am confused now: in your code:

```
        target["size"] = torch.as_tensor([int(h), int(w)])

        return image, target
```


target is actually h, w, but you using

```
  h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
                           torch.stack([inst['size'] for inst in samples[1]])[:, 0]], dim=-1)
```

1 and 0 , it should output wh..... rather than hw??

**Comment by Bertjackcai** [comment]
I have the same question of h_w, When I change the h_w to this:

        h_w = torch.stack([torch.tensor([inst.shape[-2] for inst in samples.tensors]), torch.tensor([inst.shape[-1] for inst in samples.tensors])], dim=-1)
        h_w = h_w.unsqueeze(0)

I have the follow errors:
Traceback (most recent call last):
  File "/home/csy/csycode/VisTR-master/main.py", line 221, in <module>
    main(args)
  File "/home/csy/csycode/VisTR-master/main.py", line 194, in main
    args.clip_max_norm)
  File "/home/csy/csycode/VisTR-master/engine.py", line 30, in train_one_epoch
    outputs = model(samples)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/csycode/VisTR-master/models/vistr.py", line 106, in forward
    hs ,points= self.transformer(src_proj, mask, self.query_embed.weight, pos,h_w)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/csycode/VisTR-master/models/transformer.py", line 77, in forward
    pos=pos_embed, query_pos=query_embed)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/csycode/VisTR-master/models/transformer.py", line 132, in forward
    pos=pos, query_pos=query_pos, point_ref_previous=point_sigmoid_ref
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/csycode/VisTR-master/models/transformer.py", line 357, in forward
    point_ref_previous)
  File "/home/csy/csycode/VisTR-master/models/transformer.py", line 273, in forward_post
    point_sigmoid_ref_inter = self.point1(out)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/csycode/VisTR-master/models/transformer.py", line 371, in forward
    x = F.relu(layer(x)) if i < self.num_layers - 1 else layer(x)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/csy/miniconda3/envs/vistr/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())

RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by Shengyuan-Cai** [comment]
I have the same question of h_w, When I change the h_w to this:

    h_w = torch.stack([torch.tensor([inst.shape[-2] for inst in samples.tensors]), torch.tensor([inst.shape[-1] for inst in samples.tensors])], dim=-1)
    h_w = h_w.unsqueeze(0)

I have the follow errors:

    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by Shengyuan-Cai** [comment]
In addition, I found that if 'NestedTensor' were to call h, w of Tensor; 

        h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
                           torch.stack([inst['size'] for inst in samples[1]])[:, 0]], dim=-1)
        h_w = h_w.unsqueeze(0)

would not be directly indexed and would report the following 
error:

    h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
TypeError: 'NestedTensor' object does not support indexing

**Comment by yformer** [comment]
> @yformer @gaopengcuhk I am confused now: in your code:
> 
> ```
>         target["size"] = torch.as_tensor([int(h), int(w)])
> 
>         return image, target
> ```
> 
> target is actually h, w, but you using
> 
> ```
>   h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
>                            torch.stack([inst['size'] for inst in samples[1]])[:, 0]], dim=-1)
> ```
> 
> 1 and 0 , it should output wh..... rather than hw??

Yeah, it looks wh from the original code.

**Comment by yformer** [comment]
> @yformer @gaopengcuhk I am confused now: in your code:
> 
> ```
>         target["size"] = torch.as_tensor([int(h), int(w)])
> 
>         return image, target
> ```
> 
> target is actually h, w, but you using
> 
> ```
>   h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
>                            torch.stack([inst['size'] for inst in samples[1]])[:, 0]], dim=-1)
> ```
> 
> 1 and 0 , it should output wh..... rather than hw??

Do you know why they need samples[1] instead of directly using samples[0] ?

**Comment by yformer** [comment]
> In addition, I found that if 'NestedTensor' were to call h, w of Tensor;
> 
> ```
>     h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
>                        torch.stack([inst['size'] for inst in samples[1]])[:, 0]], dim=-1)
>     h_w = h_w.unsqueeze(0)
> ```
> 
> would not be directly indexed and would report the following error:
> 
> ```
> h_w = torch.stack([torch.stack([inst['size'] for inst in samples[1]])[:, 1],
> ```
> 
> TypeError: 'NestedTensor' object does not support indexing

There are some issues about the code. I am figuring out what is the issue.

**Comment by lucasjinreal** [comment]
@yformer It might becaused of sizes changed after augmentation but he wants original input size as reference
